name: 'Coffee-Readme'
author: 'Akos Balasko'
description: 'Your Buy Me A Coffee Donations and Messages pushed into your Readme.md'

inputs:
  BUY_ME_A_COFFEE_TOKEN:  # id of input
    description: 'Your Buy Me A Coffee token'
    required: true
  
  GH_TOKEN:
    description: "GitHub access token with Repo scope"
    default: ${{ github.token }}
    required: true

  README:
    description: "Case sensitive name of your readme.md "
    default: "README.md"

  COMMIT_MESSAGE:
    description: "Add a commit message of your choice"
    default: "Buy me a Coffee messages updated"
    required: false

  NUMBER_OF_MESSAGES: 
    description: 'Number of the messages to show'
    default: 3

  BRANCH:
    description: 'Branch to be updated'
    default: main


runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-node@v3.8.1
    - run: ls -la
      shell: bash
    - uses: akosbalasko/coffee-to-file@1.0.1
      with:
        BUY_ME_A_COFFEE_TOKEN: ${{ inputs.BUY_ME_A_COFFEE_TOKEN }}
        NUMBER_OF_MESSAGES: ${{ inputs.NUMBER_OF_MESSAGES }}
        FILENAME: ${{ inputs.README }}
    - uses: stefanzweifel/git-auto-commit-action@v4.16.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        file_pattern: ${{ inputs.README }}
        commit_message: ${{ inputs.COMMIT_MESSAGE }}
        branch: ${{ inputs.BRANCH }}
        commit_user_name: Buy Me a Coffee Readme action
        commit_user_email: noreply@buymeacoffeereadmeaction.com

branding:
  icon: "award"
  color: "yellow"