name: 'PR & Issues Title Verify'
description: 'Check PR and Issues title against a regex'
author: 'Ludy87'
inputs:
  issues_pattern:
    required: false
    description: 'regex pattern to match against'
  issues_pattern_flags:
    required: false
    description: 'flags for the regex input'
  issues_min_length:
    description: 'Min length of title'
    required: false
    default: '1'
  issues_max_length:
    description: 'Max length of title. -1 to ignore the rule'
    required: false
    default: '-1'
  issues_labels:
    default: Title invalid, Stale
  issues_comment:
    required: false
  token:
    default: ${{ github.token }}
    required: true
    description: 'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'check'
  color: 'green'
